### ISSUE TITLE
Add ability to unshrink images on all notes

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/editor-image-size#2]
Can we add an option when right clicking on notes in the browser to unshrink them all?  Would basically just be a find and replace I'm guessing?

@RisingOrange if you're able to add this?  Doesn't need to be a big priority

**Comment by RisingOrange** [comment]
Added it: https://github.com/AnKingMed/editor-image-size/releases/tag/0.3

The name of the action is `Expand Images`.

**Comment by AnKingMed** [comment]
Awesome! Thank you
