### ISSUE TITLE
When browsing a specific term or card, the add on does not work, if a solution could be found that would be great. 

### ISSUE THREAD

**Issue by talkael** [AnKingMed/editor-image-size#3]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."*

#### Solution

*Concisely describe the solution you would like*

*Concisely describe alternatives you've considered (if any)*

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by RisingOrange** [comment]
I just uploaded a new version of the add-on to AnkiWeb that maybe fixes this error. You may have to check for updates to make Anki download it (Tools -> Add-ons -> Check for Updates).

If it still doesn't work can you send me the contents of the card you tried it on? 
You can do that by selecting the card in the browser, opening the HTML editor (top right corner of the field in the editor) and copying the contents of the fields and posting them here.
